swipe:
  3: 
    left:
      command: 'xdotool key Alt_L+Shift+Tab'
    right:
      command: 'xdotool key Alt_L+Tab'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super+h'
  4:
    left: 
      command: 'xdotool key XF86AudioLowerVolume'
    right: 
      command: 'xdotool key XF86AudioRaiseVolume'
    up: 
      command: 'xdotool key ctrl+j'
    down: 
      command: 'xdotool key ctrl+k'
pinch:

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
